name: NSE OI Sprut to Google Sheet

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: |
          pip install -r requirements.txt

      - name: 🔐 Set Google credentials env
        run: |
          echo "NEW<<EOF" >> $GITHUB_ENV
          echo '${{ secrets.NEW }}' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: 🚀 Run AI script
        run: |
          python ai.py
      - name: 🚀 Run NSE script
        run: |
          python nsesprut.py
          
      - name: 🚀 Run NSE script
        run: |
          python nifty.py

